"""
Django settings for DailyFresh project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '20ugv+y$vf6(nmwd963xfywf29ja^cd18(fc0xdq6@o8@cfs6p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 1.1 注册app应用DailyFresh_user
    'DailyFresh_user',
    # 2.1 注册app应用DailyFresh_goods
    'DailyFresh_goods',
    # 3.1 注册富文本编辑器
    'tinymce',
    # 4.1 注册文本索引
    'haystack',
    # 5.1 注册购物车
    'DailyFresh_cart',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'DailyFresh_user.middleware.UrlPathMiddleware',
)

ROOT_URLCONF = 'DailyFresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 1.2.0设置模板文件夹路径
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DailyFresh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # 1.3.0更改数据库配置为mysql数据库
        'ENGINE' : 'django.db.backends.mysql',
        'NAME' : 'DailyFresh',
        'HOST' : 'localhost',
        'PORT' : '3306',
        'USER' : 'root',
        'PASSWORD' : 'mysql',



    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

# 1.4.0更改语言'en-us'为中文
LANGUAGE_CODE =  'zh-Hans' 

# 1.4.1更改时区'UTC'为亚洲中国上海时区
TIME_ZONE = 'Asia/Shanghai' 

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
# 1.5.0添加静态文件查找目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# 2.2 配置商品文件目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'static')


# 3.2 配置富文本编辑器
TINYMCE_DEFAULT_CONFIG = {
    'theme' : 'advanced',
    'width' : 600,
    'height' : 400,
}


# 4.2 配置搜索引擎
HAYSTACK_CONNECTIONS = {
    'default': {
        #使用whoosh引擎
        'ENGINE': 'haystack.backends.whoosh_cn_backend.WhooshEngine',
        #索引文件路径
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    }
}
#当添加、修改、删除数据时，自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
# 每页搜索显示的个数
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 12